### ISSUE TITLE
Choose color preset with live update on the bulb

### ISSUE THREAD

**Issue by ipa64** [DCMaxxx/LIFX-Widget#1]
Hi, at first thanks for this useful application!
I think that can be more easier when you select a preset color to be able see it in live on the bulb.
Thanks

**Comment by DCMaxxx** [comment]
It has been added in [#8cdd0b8e](https://github.com/DCMaxxx/LIFX-Widget/commit/8cdd0b8e626c2d6da95051a484bdfe22d4ba839f).
Will ship in next release by the end of the month :).

**Comment by ipa64** [comment]
Good news 
Thank you



Le 20 mars 2015 à 01:36, Maxime de Chalendar <notifications@github.com> a écrit :

It has been added in #8cdd0b8e.
Will ship in next release by the end of the month :).
