### ISSUE TITLE
"Unable to load"

### ISSUE THREAD

**Issue by alanhogan** [DCMaxxx/LIFX-Widget#3]
This has been happening lately. 

The widget will show up as expected, then kind of flicker and re-draw, and then it is entirely replaced with this message. 

I have 4 LIFX bulbs on the network. 

![error message](http://f.cl.ly/items/0D0B2Y0z0B1W3p2F1Q2X/Image.jpg)

**Comment by DCMaxxx** [comment]
Hi,

TL;DR: I'm on it.

I'm really sorry for the inconvenience, but this is a bug in LIFXKit, and I'm working on a complete rewrite of the code to make it work again...

I wanted to push an update last weekend but there's more work than I expected. 
I also develop for a living and I have a lot of work, so I am only able to work a couple of hours a day on it after work.

I've already re-wrote the LIFX API (using the HTTP beta API), and I hope I'll be able to push an update this week, if everything goes well.


Max.

**Comment by alanhogan** [comment]
Impressive. Thanks for a useful app!

Alan

**Comment by DCMaxxx** [comment]
I don't know if you have seen it yet, but a V2 is out and uses the HTTP API.

**Comment by alanhogan** [comment]
Awesome! Downloaded. Will try it out soon!

**Comment by alanhogan** [comment]
Getting past this step seems to be impossible. I can’t copy the code as text. Pasting it into Notes yields some table or something, and pasting into a text-only input yields nothing. 

I blame the jokers at LIFX. Wow. Really infuriating mobile "experience" they whipped up here. Totally unusable. 

Please let me know if you have a workaround. I tweeted at LIFX about this. Hopefully it ends up on their radar. 





Alan

**Comment by DCMaxxx** [comment]
Hi,

Yeah, I dunno if it's iOS or LIFX to blame, but have a look at here, somebody is having the same issue and we've fixed it :
[Issue #4](https://github.com/DCMaxxx/LIFX-Widget/issues/4) (see my answer)
