### ISSUE TITLE
LIFX Widget does not identify token

### ISSUE THREAD

**Issue by blibbler** [DCMaxxx/LIFX-Widget#4]
The lifx widget app does not appear to be able to detect the token. I follow the steps (login, generate token, copy it), but the app says that it looks like I have failed to copy it. When I confirm that I have copied it, it still does not work.
I think what might be happening is the token appears in a table, and iOS only lets me copy the table, and not the text within the table. I have used different programs to extract the text of the token, but I cannot get the widget app to accept it. Am I missing something, or has something changed on the lifx backend to stop the program working?

**Comment by DCMaxxx** [comment]
I just generated a token and it seems to work for me.

Have you validated using the "Generate" button or "Done" on the keyboard ?
If you validate pressing the Done button, iOS does indeed copy the table and the pasteboard only contains a blank line.
If you validate using the Generate button, you can copy the full token and it should work.

If it still doesn't work, you can try :
1- Generate a token on the web (http://cloud.lifx.com/settings)
2- Send it on your iPhone by mail, message, whatever, and copy it
3- Open LIFX Cloud in LIFX Widget
4- Press the Done button (as the token is already in the past board, it shouldn't complain)

Let me know how it goes

Max.

**Comment by blibbler** [comment]
Thanks. The second one worked great.

**Comment by DCMaxxx** [comment]
Weird that the first one didn't work. Which device / iOS version are you using ? I'll try to reproduce.

**Comment by blibbler** [comment]
I must admit didn't try the first option because I didn't want to have to enter my lifx password by hand again (I store it all in 1password). I figure I must have clicked on the "done" button previously as you suspected.

**Comment by DCMaxxx** [comment]
Okay, cool, thanks for the infos.

**Comment by alanhogan** [comment]
I tried "option #1" (generate button instead of dismissing keyboard with Done or Go (enter)) and it worked. So strange. Thanks for your help and patience. 

Hey @blibbler I’m also a 1password user. I pasted my password in. Do you have their iOS app? It’s awesome
